.TH PRINTF 3 2021-11-9 GNU

.SH NAME

_printf

.SH SYNOPSIS
.B Header File

#include "main.h"

.B Prototypes

int _printf(const char *format, ...);

int get_print(char c, va_list *vl);

int print_string(char *);

int print_int(int);

int _putchar(char);

int accInt(va_list *);

int accString(va_list *)

int accChar(va_list *);

int accPercent(va_list *vl);

.B Struct

char letter;

int (*print)(va_list *);

.RE
.SH DESCRIPTION
The current function prints:

.B Strings(s)
 are array of characters

.B Characters(c)
 It denotates any alphabet, digit or symbol used to represent information.

.B Integers(i): whole number with various ranges.

.B Decimal Numbers(d): Numbers in decimal base.

.B %: specifiers

.SH Conversion specifiers
.TP
.BR \-d "," \ -i
The int argument is converted to signed decimal notation. The precision, if any, gives the minimum number of digits that must appear,
if the converted value requires fewer digits, it is padded on the left with zeros.
.TP
.BR -c
The int argument is covered to an unsigned char, and the resulting character is written.
.TP
.BR -s
The const char * argument is expected to be a pointer to an array of character type.
.TP
.BR -%
A '%' is written. No argument is converted. The complete conversion specification is '%%'.


.SH RETURN VALUE

Upon succesful return, these functions returns the number of characters printed.

.SH EXAMPLE

.EX #include "main.h"

int main(void)
{
	char c = 'H';
	int i = 2021;
	char *s = "Printf Proyect";

	_printf("%colberton School, Nov 09, %d, %s\n", c, i, s);
	return (0);
}
.EE
.SH OUTPUT

Holberton School, Nov 09, 2021, Printf Proyect

.SH AUTHORS

Gabriel Lopez Ruiz & Jose Andres Fabre Lopez
